export { default as AdminLayout } from './AdminLayout'
export { default as CreateProduct } from './CreateProduct'
export { default as ManageProduct } from './ManageProduct'
export { default as ManageOder } from './ManageOder'
export { default as Dashboard } from './Dashboard'
export { default as ManageUser } from './ManageUser'
export { default as UpdateProduct } from './UpdateProduct'